### ISSUE TITLE
Feature: Templates Unmoderated Tests

### ISSUE THREAD

**Issue by TalesAugusto1** [ruxailab/RUXAILAB#153]
_(description edited by @KarinePistili )_
Let me try to give a better explanation of what we want to do. Here it is:

1. First: What is the **unmoderate test**? 
- You can create one by clicking on (+) > Create a blank test > Usability User > SelfTest
- You will have to fill it up with some mock data first, so you have some data to work with

![image](https://github.com/ruxailab/RUXAILAB/assets/43211581/6a60af2a-de9d-4baa-a518-c3d182cc72a2)
![image](https://github.com/ruxailab/RUXAILAB/assets/43211581/45bd8fc5-ea94-4e11-aa27-7cc05bfc4c58)
![image](https://github.com/ruxailab/RUXAILAB/assets/43211581/47534001-a5cf-412c-b3d9-7abeccc58baa)

2. There is already a button to **Create Template** on **Settings** tab
- This button creates a template
- But if we try to create a test with it, it does not work properly
![image](https://github.com/ruxailab/RUXAILAB/assets/43211581/347ec283-fe32-4263-b56b-5d72af44de1b)

3. The objective of this issue is to:
- Fix the creation of Unmoderated Usability Tests using a template
- Fix deleting a template
- Add logic to **edit** this type of template

I'll put this on the issue description as well ;)

**Comment by Tejashwi1** [comment]
I would like to take up this issue @jvJUCA

**Comment by Jaishree2310** [comment]
Hey @jvJUCA  if this issue is still open I would like to go ahead and make the changes

**Comment by Anujvaid45** [comment]
Hi @jvJUCA @TalesAugusto1 
I read the issue and I even saw the concerned page.
what i found is that we can actually create a test from templates page. So can you shed some extra light regarding what exactly needs to be done?
Also the second task says template is not being saved ,but that also is not the case it seems
It would be really beneficial if you could provide few more details regarding this

**Comment by jvJUCA** [comment]
> Hey @jvJUCA if this issue is still open I would like to go ahead and make the changes

Ok, assigned!

**Comment by Jaishree2310** [comment]
> Hi @jvJUCA @TalesAugusto1 I read the issue and I even saw the concerned page. what i found is that we can actually create a test from templates page. So can you shed some extra light regarding what exactly needs to be done? Also the second task says template is not being saved ,but that also is not the case it seems It would be really beneficial if you could provide few more details regarding this


I have the same question, @jvJUCA @TalesAugusto1 can you please elaborate more?

**Comment by jvJUCA** [comment]
Dear @Jaishree2310,

The issue at hand pertains to creating a test from a template. Currently, only the heuristic test possesses this capability. I'll rename the issue to make it clearer, but it revolves around creating templates for async unmoderated tests. If you believe you can handle this issue, please let me know!

Work on templates for moderated tests is slated for the future since the moderated test is still undergoing structural development. Hence, if you decide to tackle this issue, focus solely on templates for unmoderated tests!

Best regards,

@jvJUCA

**Comment by Jaishree2310** [comment]
Hi @jvJUCA, 
This feature sounds interesting as it will help enhance test efficiency and save our users time. 
I'm working on this issue. Before I get too far, I wanted to run my plan by you to ensure we're on the same page. I have also completed by local setup

Here's what I'm thinking:
1. Design a wireframe/ UI for creating and selecting templates during test creation
2. Get a feedback on designs
3. Implement UI
4. Backend functionality to store, retrieve, and use templates.
5. Testing by writing unit and integration tests
6. Documentation parallelly

Does this align with your vision for the feature? Are there any specific points you'd like me to focus on?

**Comment by jvJUCA** [comment]
Dear @Jaishree2310,

Thank you for taking the initiative on this issue and for sharing your plan with me. Your proposed approach sounds comprehensive and aligns well with what we aim to achieve with this feature.

I appreciate the thoughtfulness you've put into considering the various aspects of design, implementation, testing, and documentation. It's great to see that you've already completed your local setup as well.

I fully support your plan and believe that dedicating your efforts to this issue will be highly beneficial. If there are any specific areas where you feel you need additional input or assistance, please don't hesitate to reach out.

Looking forward to seeing the progress!

Best regards,
jvJUCA

**Comment by Jaishree2310** [comment]
Hi, @KarinePistili @jvJUCA  Can you please take a look at this design and let me know what else can i make changes and what should i add to it? 
![Screenshot 2024-03-24 235344](https://github.com/ruxailab/RUXAILAB/assets/73012522/97648756-9005-4b40-ad1c-4159b83272a9)
![Page](https://github.com/ruxailab/RUXAILAB/assets/73012522/af0afead-1dfe-491f-9c1b-d8ace1b02cf4)

Introducing a new template feature to support unmoderated tests, with a plan that encompasses: identifying key test types for template development, creating an intuitive UI for easy template customization, conducting beta testing to refine the feature, launching with comprehensive user guides, and continuously improving the template library based on user feedback. This approach ensures our platform remains responsive and aligned with user needs.

**Comment by KarinePistili** [comment]
@Jaishree2310 I believe you will need to make it more integrated with ruxailab, so we can have a better image of your idea. Try to create some flows alongside what already exists within ruxailab.

**Comment by Jaishree2310** [comment]
> @Jaishree2310 I believe you will need to make it more integrated with ruxailab, so we can have a better image of your idea. Try to create some flows alongside what already exists within ruxailab.

Thanks, Karine, I will share a similar idea with the existing Ruxailab design.

**Comment by Jaishree2310** [comment]
Hi, @KarinePistili @jvJUCA  I need some help with the design as from what I can see with the existing Figma file of RUXAILAB the unmoderated test is showing two screens like the moderator screen and user screen test. Also what I think is that the task, pre-test, and post-test have a moderated view and a task view.  What kind of template that i can make for this?

--
Another question was ->
Can I add something like below for a predefined template?
Tasks:

Task 1: [Description of the task for eg, Sign up for an account.]
Questions:
Was the sign-up process intuitive? Why or why not?
Did you encounter any difficulties? If so, please describe.

Task 2: [Another task, e.g., Locate and use the search feature.]
Questions:
How easy was it to find the search feature?
Describe your experience using the search feature.

**Comment by Jaishree2310** [comment]
I am viewing this Figma file https://www.figma.com/file/DIRwWxc0CeAAmC47X2jp7D/Untitled?type=design&node-id=0-1&mode=design&t=SR0s7Q6YuqmBdEGB-0
 If there is any other updated design please share the file with me to better resolve this issue.
 Thank you!

**Comment by jvJUCA** [comment]
Dear @Jaishree2310, 
you just need to do the possibility to create a unmoderated test with a template like you can create with a heuristic test, just that your work is to make a logic to create a template of an existing unmoderated test, and make another tests using this template.

Hope i help,
@jvJUCA

**Comment by Jaishree2310** [comment]
Hi, @jvJUCA When I have added 2 tasks unmoderated in the current system what I see is that when I enter the details of task 1 and then press okay it doesn't go directly to task 2 and post-test. I have to manually go and press task 2 and fill in the details.
 Also while filling in details there is always a save button that appears and then again on the right bottom of the screen, there is a save button that I need to press again for saving. 
Another thing when I first created a task I was confused with the submit button then found the button on the right side in the icon where there are 2 options to save and submit. (What I think over here is that for a good user experience submit button should be in the middle of the bottom page for smooth function so users will not waste their time while searching for the next step or the submit button.

**Comment by jvJUCA** [comment]
Dear @Jaishree2310,

thank you for the detailed feedback! We are already aware of these issues, and they are being addressed in other branches that are currently being merged with the development branch. Therefore, there's no need to make these additional changes at the moment. We appreciate your observations and your contribution to improving the user experience!

Best regards,
@jvJUCA

**Comment by Jaishree2310** [comment]
Hi, @jvJUCA  I know you have helped me a lot with this issue but I am still a bit confused with the interface design. 
This is how it looks when we go for the heuristic template. Do I have to create a template like this for the unmoderated test?
If not then please help me with more understanding of how the template design for the unmoderated test you want, I will try my best to make that.
![Screenshot 2024-04-07 221715](https://github.com/ruxailab/RUXAILAB/assets/73012522/437122ef-baf8-4896-ba00-893ffc032cd3)

**Comment by KarinePistili** [comment]
Hello @Jaishree2310 !! Let me try to give a better explanation of what we want to do. Here it is:

1. First: What is the **unmoderate test**? 
- You can create one by clicking on (+) > Create a blank test > Usability User > SelfTest
- You will have to fill it up with some mock data first, so you have some data to work with

![image](https://github.com/ruxailab/RUXAILAB/assets/43211581/6a60af2a-de9d-4baa-a518-c3d182cc72a2)
![image](https://github.com/ruxailab/RUXAILAB/assets/43211581/45bd8fc5-ea94-4e11-aa27-7cc05bfc4c58)
![image](https://github.com/ruxailab/RUXAILAB/assets/43211581/47534001-a5cf-412c-b3d9-7abeccc58baa)

2. There is already a button to **Create Template** on **Settings** tab
- This button creates a template
- But if we try to create a test with it, it does not work properly
![image](https://github.com/ruxailab/RUXAILAB/assets/43211581/347ec283-fe32-4263-b56b-5d72af44de1b)

3. The objective of this issue is to:
- Fix the creation of Unmoderated Usability Tests using a template
- Fix deleting a template
- Add logic to edit this type of template

I'll put this on the issue description as well ;)
