### ISSUE TITLE
Feat: Implement weight system on heuristic evaluation

### ISSUE THREAD

**Issue by KarinePistili** [ruxailab/RUXAILAB#225]
- [x] Implement weight definition on heuristic's creation
- [x] Implement calculation of weight on answers results

**Comment by Jaishree2310** [comment]
Hi, @KarinePistili What I see in the heuristic evaluation is that the weight is empty. 
What exactly it should look like?
![Screenshot 2024-03-24 234543](https://github.com/ruxailab/RUXAILAB/assets/73012522/9e10ac1e-7f20-4233-a5c4-56f58951ea5e)

**Comment by KarinePistili** [comment]
Hello @Jaishree2310 , you need to have at least 2 heuristics created so they appear on the the weights

**Comment by Jaishree2310** [comment]
Okay got it!
