### ISSUE TITLE
Heuristic index not refreshing when deleted.

### ISSUE THREAD

**Issue by FernandaCasali** [ruxailab/RUXAILAB#278]
![image](https://github.com/uramakilab/remote-usability-lab/assets/145176268/40c6df8f-f4a1-4580-986e-207f006bdc33)

I'm using the weightTable branch

**Comment by mohitbalwani** [comment]
Hi @jvJUCA , are you working on this issue? I am curious to know what this issue is all about. I tried searching for weightTable branch but I didn't found it in this repository. Let me know if you want me to work on it or you need any type of help in it!
cc @FernandaCasali
