### ISSUE TITLE
Implement AI-powered Dashboard for Response Visualization

### ISSUE THREAD

**Issue by jvJUCA** [ruxailab/RUXAILAB#295]
- Implement a dashboard or data visualization tool that leverages AI-generated insights to visualize qualitative user data effectively.
- Develop interactive visualizations, such as word clouds, sentiment heatmaps, and topic clusters, to provide an overview of user feedback patterns.
- Enable researchers to explore and drill down into individual responses or thematic clusters to gain deeper insights into user perceptions and preferences.
- Ensure the responsiveness and accessibility of the AI-powered dashboard across different devices and screen sizes.

**Comment by duplixx** [comment]
@jvJUCA I would like to work upon  this issue

**Comment by marcgc21** [comment]
@barkhaaroraa @duplixx right now this issue it can only be related to our eye-tracker python repository which where we worked to create a regression linear system that helps us to track the eye of the users. However we failed a little bit about how to do that. If you can start taking a look on that repository and give your opinions should be great!
https://github.com/ruxailab/web-eye-tracker

**Comment by duplixx** [comment]
yeah sure
