### ISSUE TITLE
Fix: Erros in console of TestAnswersDocLength

### ISSUE THREAD

**Issue by jvJUCA** [ruxailab/RUXAILAB#302]
In EditTestView is showing too much same errors in console like: 

![Captura de ecrã de 2024-02-01 14-49-57](https://github.com/uramakilab/RUXAILAB/assets/128351990/a0ed2636-99b9-4c4d-a680-4ce63ad7dce2)

**Comment by varunsh17** [comment]
I have experience in Vuejs, would like to work upon this @jvJUCA
