### ISSUE TITLE
Router Guard to other accounts in someones test

### ISSUE THREAD

**Issue by jvJUCA** [ruxailab/RUXAILAB#303]
If someone uses your test link in RUXAILAB, he can answer your test without being invited, someone who uses a link like that is like  a 'guest' for the router guard, **fix this to don't allow this.**

**Comment by skushagra9** [comment]
I am interested to work on this

**Comment by marcgc21** [comment]
@skushagra9 this is the best way to start getting in touch with the project, if you want I can assign it to you and let see if you can fix it!

Let us know if you need more information from @jvJUCA

**Comment by kirtanchandak** [comment]
Hey @skushagra9 are you still working on this? If not I can take this up!

**Comment by skushagra9** [comment]
yes, I am working on this

**Comment by KarinePistili** [comment]
@skushagra9 do you have any questions? feel free to ask them

**Comment by skushagra9** [comment]
no worries, there was some problem in setting up the codebase locally, but now its resolved

**Comment by skushagra9** [comment]
Hey, I am very near to the solution
For the fix, should I display an error message, like - you don't have permissions as you are a guest

**Comment by KarinePistili** [comment]
Nice! Yes it can be like that

**Comment by vishav-singla** [comment]
Is this issue resolved?

**Comment by vishavsingla** [comment]
Is this issue resolved?

**Comment by KarinePistili** [comment]
Added @vishavsingla as assignee as it is being worked on the PR
