### ISSUE TITLE
[🐞 BUG]: We get redirected to home page after login and see nothing.

### ISSUE THREAD

**Issue by skbhagat0502** [ruxailab/RUXAILAB#316]
### Description 📝

After login we get redirected to home page and see nothing except User Home. 

### Link 🔗

/home

### Steps to Reproduce 🔄

Login to the website. We can the home page with the text User Home and nothing.

### Screenshots 📸

![Screenshot 2024-02-26 003231](https://github.com/ruxailab/RUXAILAB/assets/109683163/8de99128-ea65-4c8a-882b-b91aea01bc54)

### Expected Behavior 🤔

Actually before assuming the expected behavior I thing there should be discussion for this issue. Actually what needs to be done.

### Actual Behavior 😱

After login we get redirected to home page and see nothing except User Home. we can see the screenshot.

### Environment 🌍

N/A

**Comment by skbhagat0502** [comment]
@marcgc21 @sergiobeltranguerrero Please tell me what is your point of view. Is this a bug realy or this is the expected behavior. How to contribute if I will land in to the home page only. Contributors should be provided some userId and password for different level. So that they can login and solve and discuss potential bugs.

I want to solve this issue. Please share your thoughts.

**Comment by sergiobeltranguerrero** [comment]
@jvJUCA can you help us? 
is the expected behaviour?

**Comment by jvJUCA** [comment]
Check if the your node packages are installed, and your .env is successfully configured, if you can show the console will help :+1:

**Comment by skbhagat0502** [comment]
Actually there is no bugs as there are levels defined for each users. Like super admin level is 0. Admin level is 1. And user level is 0. The website shows the page according to the user level. And hence this page is shown. How can I register my self as a super admin or admin.

**Comment by skbhagat0502** [comment]
![image](https://github.com/ruxailab/RUXAILAB/assets/109683163/242c680d-f20a-40d4-a823-050fbaee9917)
seet I have linked the screenshot of the console.
@jvJUCA @sergiobeltranguerrero

**Comment by jvJUCA** [comment]
Dear @skbhagat0502 ,

I responded with suggestions on how to address the access level issue in the discussions. I would appreciate it if you could take a look and provide your feedback.

Best regards,

@jvJUCA

**Comment by skbhagat0502** [comment]
@jvJUCA I saw your suggestions but there is no from my side. I might have seen to wrong discussion. Can you please share the exact discussion link.

**Comment by jvJUCA** [comment]
Sharing the URL of the discussion @skbhagat0502 

https://github.com/ruxailab/RUXAILAB/discussions/313

I hope it will help you to solve this problem.

@jvJUCA

**Comment by Crazyraturi** [comment]
@skbhagat0502  what email id or password you use to login or replicate this issue.
if i use my  login E-mail and password it say wrong gmail and password(error)

**Comment by skbhagat0502** [comment]
@Crazyraturi First register yourself then login.

**Comment by rohit9625** [comment]
I registered and then tried with the correct credentials but still faced an incorrect password or username which was in the Portuguese language.

**Comment by rohit9625** [comment]
The account is not created for the user when signing up. But, it lets us redirect to in page even in the console where these errors are encountered.
![image](https://github.com/ruxailab/RUXAILAB/assets/101377978/5ea5934b-5e9b-40ff-bb0a-04f895e3aeb9)

**Comment by rohit9625** [comment]
I added all the required details as mentioned in the docs.

**Comment by ProgrammingPirates** [comment]
@sergiobeltranguerrero  Can you assign me this issue please ?

**Comment by rohit9625** [comment]
I suggest you to first setup the development environment first :)

**Comment by jvJUCA** [comment]
<a href='https://youtu.be/dAf4LRxITCc'>Tutorial - Running RUXAILAB with Firebase Emulators   🖥️</a>
