### ISSUE TITLE
[🐞 BUG]:  default Portuguese translation for auth errors

### ISSUE THREAD

**Issue by Gaurav-Verma07** [ruxailab/RUXAILAB#318]
### Description 📝

Default lang. as Portuguese in auth popup instead of selected lang.

### Link 🔗

/signin

### Steps to Reproduce 🔄

1. Go to login page.
2. Select `english` as default language.
3. Enter incorrect credentials and clink SIGN-IN.
4. A popup appears in portuguese lang.

### Screenshots 📸

![image](https://github.com/ruxailab/RUXAILAB/assets/63046396/ef5ebd6d-42b0-4846-a6fb-f03b9a5f78b9)

### Expected Behavior 🤔

The popup text should be in eng. lang or selected language.

### Actual Behavior 😱

Popup text is in Portuguese lang. irrespective of selected lang.

### Environment 🌍

- Vue Component- `src/views/public/SignInView.vue`

**Comment by Gaurav-Verma07** [comment]
Hey @jvJUCA  I can resolve this

**Comment by jvJUCA** [comment]
Ok, i will assign you, this is a i18n problem, the text in the alert is hardcoded in portuguese. :+1:
