### ISSUE TITLE
User login test

### ISSUE THREAD

**Issue by sergiobeltranguerrero** [ruxailab/RUXAILAB#322]

**Comment by Gaurav-Verma07** [comment]
Could you please provide more info regarding the issue? I'd like to work on this

**Comment by sergiobeltranguerrero** [comment]
I'm very glad that you want to work on this test. But first, I want to establish a basic test guide. Later when i have these tests, I will generete more issues about the tests.
Thanks 😊

**Comment by Gaurav-Verma07** [comment]
Sure, let me know if I can be of any assistance

**Comment by ProgrammingPirates** [comment]
Hello sir @sergiobeltranguerrero ,i want to start my contribution on this organization, can you please assign me this issue.

**Comment by sergiobeltranguerrero** [comment]
Hi @Gaurav-Verma07 and @ProgrammingPirates I am trying to run the tests in jest and testing library. But there is something I am doing wrong and I think it is because I am not mocking the router. Can you help me?
My code is:

```
describe('SingIn', () => {
  it('should display username input', async () => {
    render(CardSignIn)
    const input = screen.getByLabelText(/username/i)
    expect(input).toBeInTheDocument()
  })
})
```

**Comment by Gaurav-Verma07** [comment]
Hii @sergiobeltranguerrero, Hope you're doing well.
With respect to the information you provided, it seems you're testing a `CardSignIn` component that renders a username input.
As per official docs https://v5.reactrouter.com/web/guides/testing, to mock the router for your test, you can use the **MemoryRouter** component from React Router. 
Try this- 
```
import { MemoryRouter } from 'react-router-dom'
describe('SingIn', () => {
  it('should display username input', async () => {
   <MemoryRouter>
    render(CardSignIn)
   </MemoryRouter>
    const input = screen.getByLabelText(/username/i)
    expect(input).toBeInTheDocument()
  })
})
```

Let me know if it helps.

**Comment by KarinePistili** [comment]
@Gaurav-Verma07 I think your suggestions is using React. This project is using Vue, so try to provide examples using the same framework :)
