### ISSUE TITLE
[✨ FEATURE]: Setting up the development environment - Documentation update

### ISSUE THREAD

**Issue by skbhagat0502** [ruxailab/RUXAILAB#323]
### Feature Description 📝

Currently contributors are facing a lot difficulty in setting up the development environment. We need to update the readme to tell the detailed process of how to setup the project.

### Motivation 🌟

I was facing a lot difficulty in setting up the project and hence I want to update the documentation on how to setup the project so that other contributors may not face difficulty.

### Expected Behavior 🤔

There will be a detailed process on how to setup the project for local development.

### Additional Information ℹ️

N/A

**Comment by skbhagat0502** [comment]
@jvJUCA @sergiobeltranguerrero Please assign me this issue.

**Comment by Gaurav-Verma07** [comment]
I also find this issue useful, especially with the firebase setup which may be quite tricky for new os contributors.

**Comment by skbhagat0502** [comment]
@jvJUCA @sergiobeltranguerrero am I doing something wrong. I am not able to see any collections of users in the firestore database and I am not able to change the access level of my self. I dont know if I am doing something wrong. 
Here are some screenshot on how I am running the project. 
![image](https://github.com/ruxailab/RUXAILAB/assets/109683163/5995c733-82d8-4aab-b06c-caad894551b7)
![Screenshot 2024-02-28 154859](https://github.com/ruxailab/RUXAILAB/assets/109683163/86474c15-ea1c-4ecf-9158-c45a10ee46bc)

**Comment by skbhagat0502** [comment]
@jvJUCA @sergiobeltranguerrero Please let me know how to resolve this issue. I will update the documents after setting up this project successfully.

**Comment by ProgrammingPirates** [comment]
@sergiobeltranguerrero @jvJUCA  can you assign me this please ?

**Comment by jvJUCA** [comment]
<a href='https://youtu.be/dAf4LRxITCc'>Tutorial - Running RUXAILAB with Firebase Emulators   🖥️</a>
