### ISSUE TITLE
[🐞 BUG]:  Unexpected behavior of `Return to Console` button

### ISSUE THREAD

**Issue by Gaurav-Verma07** [ruxailab/RUXAILAB#326]
### Description 📝

On `signin` page, the **Return to Console** button redirects user to `/` which is an expected behavior however, much better if button text here is **Go to Home** since landing page is not console.

On `signup` page, the **Return to Console** button redirects user to `/testlist` which is not an expected behavior, it should redirect to `/` route since the user should not be allowed to access `/testlist` without authentication.

### Link 🔗

/signin /signup

### Steps to Reproduce 🔄

Go to `/signin`, inspect routing behavior of **Return to Console** button

Go to `/signup`, inspect routing behavior of **Return to Console** button

### Screenshots 📸

NA

### Expected Behavior 🤔

On `/signin`, the **Return to Console** button text to **Go to Home** redirecting to `\` would be more appropriate.
Same approach for the `/signup` page.

### Actual Behavior 😱

**Return to Console** showing unexpected redirection on `signin` and `signup` page.

### Environment 🌍

Vue Component- **Toolbar.vue**
Git branch- **develop**
OS-  Ubuntu 22.04.3 LTS
Browser- Chrome

**Comment by Gaurav-Verma07** [comment]
This might be a potential bug as I saw.
I've reproduced it so I can fix it properly.

**Comment by jvJUCA** [comment]
Dear @Gaurav-Verma07 ,

I hope you're doing well!

We've encountered a bug on GitHub related to a conditional error in button path usage. Your expertise would greatly assist in resolving this issue. Could I assign it to you for further investigation?

Best regards,

@jvJUCA

**Comment by Gaurav-Verma07** [comment]
Yes, please assign me this issue.
Many Thanks
