### ISSUE TITLE
[✨ FEATURE]: Toast messages for info error and warnings.

### ISSUE THREAD

**Issue by skbhagat0502** [ruxailab/RUXAILAB#327]
### Feature Description 📝

Currently we are using window alert for any type of error or information. This not aligns with a modern web application. We can use vue toastify for this error or info alerts. Which will make the website more user friendly.

### Motivation 🌟

Due to alerts the interaction with the website stop. We have to close it before doing anything. Also it is not a good practice to show alerts for error or info messages. Hence vue toastify can be of good choice.

### Expected Behavior 🤔

We can see the demo of vue toastify here [toastify](https://www.npmjs.com/package/vue3-toastify) can be used all over the website where alerts are used.

### Additional Information ℹ️

If you thing that there can be better and more intuitive solution. Please let me know.

**Comment by skbhagat0502** [comment]
@jvJUCA Please assing me this issue.

**Comment by jvJUCA** [comment]
> @jvJUCA Please assing me this issue.

OK assigned, this update in user alerts will be such a addition to a better user experience.
