### ISSUE TITLE
[🐞 BUG]:  accessLevel set to undefined on signin

### ISSUE THREAD

**Issue by Gaurav-Verma07** [ruxailab/RUXAILAB#329]
### Description 📝

On signing of a user the `accessLevel` parameter is undefined due to which all route are redirected to `/home` by default which is not an expected behavior.
It occurs due to conditional checking at redirect() in tools.js

### Link 🔗

/signin

### Steps to Reproduce 🔄

1. Go to /signin and continue
2. user is redirected to /home by default
3. After this failing to redirect to /testslit from anywhere.

### Screenshots 📸

[Screencast from 01-03-24 03:40:21 AM IST.webm](https://github.com/ruxailab/RUXAILAB/assets/63046396/e373a6c8-e692-416e-9d51-dcc58061dcd4)

### Expected Behavior 🤔

The accessLevel parameter should not be none.

### Actual Behavior 😱

The accessLevel parameter should is none.

### Environment 🌍

Vue component- **tools.js**, **SignInView.vue**

**Comment by Gaurav-Verma07** [comment]
@jvJUCA  
Please assign me this issue.
I need additional details about importance of accessLevel parameter to resolve this.

**Comment by Gaurav-Verma07** [comment]
@jvJUCA , what you think about it??

**Comment by KarinePistili** [comment]
Hello @Gaurav-Verma07, usually this error occurs if you don't have all the emulators setup (auth, firestore, storage, functions), or if you don't have a deploy of cloud functions, which has one specific functions that is a trigger to setup access role.

Do you have all the services of emulators running? Did you deploy your cloud funtions?

If yes to any of the questions above, try to look at the logs of this functions in particular and send us the output.

**Comment by KarinePistili** [comment]
Please, refer to discussion #309. I'll be closing this and following up there.
