### ISSUE TITLE
[🐞 BUG]: log in / signup page display after login 

### ISSUE THREAD

**Issue by Raju-Mannem** [ruxailab/RUXAILAB#332]
### Description 📝

Still Showing the sigup/sigin page after a user login to the account

### Link 🔗

https://retlab-dev.firebaseapp.com/signup

### Steps to Reproduce 🔄

1. Go the signup page
2. Signup / sign in to you account
3. After succesfully login, Go to the url https://retlab-dev.firebaseapp.com/signup

### Screenshots 📸

![Screenshot 2024-03-03 192641](https://github.com/ruxailab/RUXAILAB/assets/104633105/d1476eee-2d58-4655-a80d-072f663cb231)

### Expected Behavior 🤔

After login the signup / login page have to redirect or passed

### Actual Behavior 😱

After a user login to the account the login / sign up page is still accessible

### Environment 🌍

- Browser: edge
- OS: Windows

**Comment by sushant4612** [comment]
can i take this issue ? @KarinePistili

**Comment by Raju-Mannem** [comment]
Hai @KarinePistili 
I have fixed this issue. please find the details below.
looking forward to you

**Comment by Raju-Mannem** [comment]
Hai @KarinePistili <https://github.com/KarinePistili>
Hope you are doing well
I have fixed this issue. please find the details in the repository.
looking forward to you
Thank you

**Comment by Raju-Mannem** [comment]
Hai [@KarinePistili](https://github.com/KarinePistili) <https://github.com/KarinePistili>
Hope this will finds you well.
I have fixed this issue. please find the details below.
looking forward to you
Thank you.

**Comment by HarshAgrawal1** [comment]
Can i work on this issue?

**Comment by Raju-Mannem** [comment]
Hey @HarshAgrawal1 
I resolved this issue.
Check the commits below.
Feel free to check remaining too.
