### ISSUE TITLE
[✨ FEATURE]:  Login with Google and Github

### ISSUE THREAD

**Issue by vishisht-dubey** [ruxailab/RUXAILAB#333]
### Feature Description 📝

Hii Team as of now during sign up, we can not login directly using google or using github, i would like introduce that feature where a user can i either sign up/ sign in using traditional method like email and password or they can login with the help of google and github.

### Motivation 🌟

Motivation behind this is to improve the user experience, providing them with better experience and simplifying the signing up process for faster development.

### Expected Behavior 🤔

Adding two Buttons, One for login with google and another for login with github and implementing the end to end functionality and complete working.

### Additional Information ℹ️

Is there any other suggestion upon this feature, i would love to add that suggestion as well.

**Comment by vishisht-dubey** [comment]
@marcgc21 @xemyst @KarinePistili @sergiobeltranguerrero I would like to work on this issue, if you guys approve please let me know so that i can immediately start working. Thanks.

**Comment by KarinePistili** [comment]
Hello @vishisht-dubey, thank you for your suggestion. Right now we don't have interest on implementing other types of authentication as RUXAILAB is usually used by reasearchers with institutional emails. 

Feel free to express interest to other issues with the tags **help wanted** and **gsoc related**
