### ISSUE TITLE
Enhancement: Improve Handling of Error State in Global Store

### ISSUE THREAD

**Issue by jvJUCA** [ruxailab/RUXAILAB#335]
Currently, the setError function in our global store lacks a clear method for displaying errors to users. We need to refine this to provide a better user experience.

Proposed Changes:

-  Enhance setError to include a standardized error presentation model.
-  Implement support for additional error metadata.
-  Introduce a centralized error component for consistent error display.

Objective:
By improving setError, we aim to enhance the user experience by providing clearer error messages.

setError on store:
```javascript
   setError(state, payload) {
     state.error = payload
 },
```

**Comment by Gaurav-Verma07** [comment]
Looks good @jvJUCA .
Please assign me this issue

**Comment by sushant4612** [comment]
even i am also intrested in the issue @jvJUCA

**Comment by jvJUCA** [comment]
> Looks good @jvJUCA . Please assign me this issue

Assigned to you. Ready to begin?

**Comment by sushant4612** [comment]
@jvJUCA can i also work on it ?

**Comment by Gaurav-Verma07** [comment]
> > Looks good @jvJUCA . Please assign me this issue
> 
> Assigned to you. Ready to begin?

Yes, will let you know if I need any assistance.
