### ISSUE TITLE
Enhancement: Enhance Heuristic Test with Responsive Design

### ISSUE THREAD

**Issue by jvJUCA** [ruxailab/RUXAILAB#336]
Description:
In this issue, our goal is to enhance the usability and accessibility of our heuristic tests by implementing responsive design principles. Responsive design ensures that our tests adapt seamlessly to various screen sizes and devices, providing users with an optimal viewing and interaction experience.

Objective:
By implementing responsive design across all aspects of heuristic tests, we aim to improve usability, increase engagement, and provide a seamless user experience for all users, regardless of the device they use to access our platform.

**Comment by RishabhJain0721** [comment]
Hey @jvJUCA,
I would like to work on this. Can you please assign this to me?

**Comment by jvJUCA** [comment]
> Hey @jvJUCA, I would like to work on this. Can you please assign this to me?

Ok, i will asign you in this issue.

**Comment by Gaurav-Verma07** [comment]
Hey @RishabhJain0721 
Please share the status of your work done so far.

**Comment by RishabhJain0721** [comment]
Hey @Gaurav-Verma07 
Its almost completed. I will be creating a PR soon.
