### ISSUE TITLE
Enhancement: Improve FAQ Help Center Page with Additional Q&A and How-To GIFs

### ISSUE THREAD

**Issue by jvJUCA** [ruxailab/RUXAILAB#337]
Enhancement: Enhance the FAQ Help Center Page with Additional Q&A Content and How-To GIFs, providing users with comprehensive guides on various actions and processes.

Current Help Center:
![Captura de ecrã de 2024-03-04 17-39-40](https://github.com/ruxailab/RUXAILAB/assets/128351990/7480a07e-66b2-4568-a0b3-2b7a3bc16877)

**Comment by TheMohit2003** [comment]
Hi @jvJUCA, I'm ready to start working on this task. Could you give me more details about the GIFs you want? If possible, could you share a link to another website that has a similar feature to what you're envisioning?

**Comment by jvJUCA** [comment]
> Hi @jvJUCA, I'm ready to start working on this task. Could you give me more details about the GIFs you want? If possible, could you share a link to another website that has a similar feature to what you're envisioning?

Hi @TheMohit2003 ,

Thank you for jumping in to work on this task! Regarding the GIFs, we're looking for simple demonstrations of how to perform the actions mentioned in each FAQ question. For example, if the question is about how to reset a password, the GIF would show a user navigating to the password reset page and following the steps to reset their password.

We don't have a specific website in mind for reference, but we're aiming for clear and concise GIFs that visually guide users through the process. Let me know if you have any further questions or need more clarification!

Best regards,
@jvJUCA

**Comment by hharshas** [comment]
@TheMohit2003 i am willing to help you with this, tell me with what can i ?

**Comment by TheMohit2003** [comment]
@hharshas , thank you for your help, but I can handle this myself . I have already created css classes and loading skeletons for gifs.

**Comment by abhisek-1221** [comment]
The issue has already been resolved in #366.
