### ISSUE TITLE
Implement Frontend for Cooperators Invite with Test Date and Time Sync for Moderated Tests

### ISSUE THREAD

**Issue by jvJUCA** [ruxailab/RUXAILAB#339]
Develop the frontend for inviting participants to synchronized moderated tests, including features to specify the test date and time. Example interface provided below:
![imagem](https://github.com/ruxailab/RUXAILAB/assets/128351990/9e8e5ac4-7ad3-42d3-8da7-6875f45d24c9)

**Comment by jvJUCA** [comment]
> you want it to be a popup, or fixed at the page ??

Thank you for your inquiry! I'm currently doing this issue. It's a necessary step for facilitating the invitation of evaluators to sync moderated tests. Your patience and understanding are greatly appreciated as we work to improve this feature.

**Comment by skushagra9** [comment]
oh, I also started to make some changes to this,
