### ISSUE TITLE
Implement New Design for Individual User Test Analysis (Unmoderated Tests)

### ISSUE THREAD

**Issue by jvJUCA** [ruxailab/RUXAILAB#344]
Current Designs for Individual Analysis in Unmoderated Tests:

![Captura de ecrã de 2024-03-05 14-52-20](https://github.com/ruxailab/RUXAILAB/assets/128351990/da46adfa-57e8-4553-8104-c10ba14a7d02)
![Captura de ecrã de 2024-03-05 14-52-22](https://github.com/ruxailab/RUXAILAB/assets/128351990/8de4239c-4d20-40b8-bb4e-0467c03bd0d3)

**Comment by pankaj87072** [comment]
hey @jvJUCA can i work on this issue ?

**Comment by pankaj87072** [comment]
hey @jvJUCA are you working on this issue ??
