### ISSUE TITLE
Enhancement: Implement Responsive Design for FAQ/Help Center Page

### ISSUE THREAD

**Issue by jvJUCA** [ruxailab/RUXAILAB#345]
Develop a responsive design for the FAQ/Help Center page to ensure optimal usability and accessibility across various devices. Enhancements will include adjusting layout, font sizes, and interactive elements to provide a seamless user experience on desktops, tablets, and mobile devices.

This Page located on /help:
![Captura de ecrã de 2024-03-05 15-04-11](https://github.com/ruxailab/RUXAILAB/assets/128351990/9f17c0a8-841c-46cc-9973-9b149a240f4a)

**Comment by abhisek-1221** [comment]
I would like to take up this issue @jvJUCA

**Comment by jvJUCA** [comment]
Ok, assigned.
