### ISSUE TITLE
Componentize CreateBlankView.vue File

### ISSUE THREAD

**Issue by jvJUCA** [ruxailab/RUXAILAB#347]
Transform the CreateBlankView.vue file into a set of reusable components to improve code organization and maintainability. This process involves breaking down the existing file into smaller, modular components that can be easily reused throughout the project.

**Comment by Tejashwi1** [comment]
I would like to take up this issue @jvJUCA

**Comment by jvJUCA** [comment]
Ok, assigned!

**Comment by pankaj87072** [comment]
hey @Tejashwi1 are you working on it??

**Comment by Jaishree2310** [comment]
@jvJUCA  is there any issue that is assigned and not yet completed please assign it to me. 
@Tejashwi1 if you are not working on this issue i would like to take this token.

**Comment by jvJUCA** [comment]
> @jvJUCA is there any issue that is assigned and not yet completed please assign it to me. @Tejashwi1 if you are not working on this issue i would like to take this token.

Dear @Jaishree2310,

You are currently assigned on the issue for the test templates. I hope you can contribute effectively to that issue.

Best regards,

@jvJUCA

**Comment by HarshAgrawal1** [comment]
@jvJUCA Can you please elaborate on what we need to do exactly?

**Comment by HarshAgrawal1** [comment]
CreateBlankView is Blan test one right?

**Comment by jvJUCA** [comment]
> @jvJUCA Can you please elaborate on what we need to do exactly?

Dear @HarshAgrawal1,

In this particular issue, we need to refactor the CreateBlankView.vue file by componentizing it. The objective is to break down this large and complex file into smaller components, each responsible for specific functions and sections of HTML. By doing so, we aim to improve readability, maintainability, and overall code organization.

Best regards,

@jvJUCA

**Comment by Tejashwi1** [comment]
@pankaj87072 I'm working on it

**Comment by sushant4612** [comment]
@Tejashwi1 are you still working on it ?

**Comment by RishabhJain0721** [comment]
@Tejashwi1 Kindly share the progress of this issue.

**Comment by TheShiveshNetwork** [comment]
Hey @jvJUCA since its taking time can I work on this issue?

**Comment by jvJUCA** [comment]
Hello everyone,

I'd like to address the issue that has been ongoing. If any of you believe you can contribute to resolving it more efficiently than the currently assigned contributor, please feel free to do so. Your input and effort are highly valued, and we're open to collaboration to expedite the resolution process.

Thank you for your dedication to the project.

Best regards,
@jvJUCA

**Comment by RishabhJain0721** [comment]
> Hello everyone,
> 
> I'd like to address the issue that has been ongoing. If any of you believe you can contribute to resolving it more efficiently than the currently assigned contributor, please feel free to do so. Your input and effort are highly valued, and we're open to collaboration to expedite the resolution process.
> 
> Thank you for your dedication to the project.
> 
> Best regards, @jvJUCA

Alright, I will create a PR regarding this issue soon.

**Comment by KarinePistili** [comment]
Assigning this issue to @sushant4612 who is actively working on the PR

**Comment by KarinePistili** [comment]
Related PR https://github.com/ruxailab/RUXAILAB/pull/388
