### ISSUE TITLE
Componentize views/admin folder

### ISSUE THREAD

**Issue by asr2003** [ruxailab/RUXAILAB#353]
### Feature Description 📝

I propose to componentize the **views/admin** folder in our project. Currently, the views are contained in a single file  and to improve code organization and maintainability, I suggest breaking it down into smaller, reusable components of files:

1. CooperatorsView.vue,
2. DashboardView.vue
3. ManagerView.vue
4. SettingsView.vue
5. TemplateView.vue

### Motivation 🌟

By componentizing the views folder, we can achieve the following benefits:

1. **Modularity:** Breaking down views into smaller components improves modularity, making it easier to manage and understand each part of the application.
2. **Reusability:** Components can be reused across different parts of the project, reducing redundancy and promoting consistency.
3. **Maintainability:** Smaller components are easier to maintain and update, contributing to a more maintainable codebase.

### Expected Behavior 🤔

The expected behavior is to have separate Vue.js components for each view in the views folder. Each component should encapsulate the logic and styles related to its specific view.

### Additional Information ℹ️

Will make a PRs for every file componentized as discussed above for better review and organized 

Thank you for considering this feature request! 🙌

**Comment by asr2003** [comment]
And a thing to discuss I am thinking to move the components to the components folder instead componentize in a single file. It helps in better organizing and reusuability of components.

@KarinePistili @jvJUCA What are your thoughts on this ? Glad to work under your guidance.

**Comment by varshith257** [comment]
@jvJUCA

**Comment by Jaishree2310** [comment]
Hello,
I've been closely following the discussions around improving the code organization and maintainability of the project, and I'm excited to propose componentizing the `views/admin` folder. This refactor aims to break down the current monolithic views into smaller, reusable Vue.js components, such as `CooperatorsView.vue`, `DashboardView.vue`, `ManagerView.vue`, `SettingsView.vue`, and `TemplateView.vue`.

This approach not only aligns with our goals for modularity and maintainability but also enhances the reusability of our components across the application. By encapsulating logic and styles within dedicated components, we can significantly improve the project's overall code quality and ease of maintenance.

I plan to undertake this task with careful consideration of the current codebase's structure and needs, ensuring that each component is designed with reusability and maintainability in mind. I will also document the changes thoroughly and create individual pull requests for each component to facilitate a smooth review process.

I'm eager to contribute to this important aspect of the project and would appreciate the opportunity to be assigned to this issue. I'm ready to discuss my proposed approach further and collaborate with the team to make this enhancement a success.

Thank you for considering my proposal.

**Comment by jvJUCA** [comment]
Ok, assigned @asr2003!

**Comment by asr2003** [comment]
> And a thing to discuss I am thinking to move the components to the components folder instead componentize in a single file. It helps in better organizing and reusuability of components.
> 
> @KarinePistili @jvJUCA What are your thoughts on this ? Glad to work under your guidance.

@jvJUCA Any thoughts on this?

**Comment by jvJUCA** [comment]
> > And a thing to discuss I am thinking to move the components to the components folder instead componentize in a single file. It helps in better organizing and reusuability of components.
> > @KarinePistili @jvJUCA What are your thoughts on this ? Glad to work under your guidance.
> 
> @jvJUCA Any thoughts on this?

Dear @asr2003,

Thank you for suggesting this adjustment. Currently, our project structure already includes a components folder. Within this folder, we've organized our components into organisms, molecules, and atoms, representing large, medium, and small components, respectively. This hierarchical organization has been serving us well in terms of maintaining clarity and facilitating component reusability.

Best regards,

@jvJUCA

**Comment by KarinePistili** [comment]
Hello! @asr2003 , have you worked on this? I don't remember seeing the PR, so I'm a little confused if this was already done or is a WIP.

**Comment by asr2003** [comment]
Yes, It's in WIP. Currently I have exams and will complete in next 3 days. Will work on them and submit PR in the weekend :)
