### ISSUE TITLE
Add Docker Support for Easier Project Setup and Deployment

### ISSUE THREAD

**Issue by TheMohit2003** [ruxailab/RUXAILAB#360]
### Feature Description 📝

Implement Docker support for the project to streamline the setup process, ensuring that all contributors can work within a consistent and isolated development environment. This includes creating a Dockerfile for the application and, if necessary, a docker-compose.yml file to manage multi-container setups, including the application and its database.

### Motivation 🌟

The motivation behind this proposal stems from numerous setup issues faced by contributors, attributed to varying system configurations and dependency management challenges. These issues not only hinder new contributors from setting up the project efficiently but also introduce inconsistencies across development environments.

### Expected Behavior 🤔

- Contributor should be able to set up the project with minimal steps, essentially requiring only Docker installation and running a couple of docker commands

**Comment by TheMohit2003** [comment]
@jvJUCA , what do you think of this ?

**Comment by ritikprajapat21** [comment]
Hi, @TheMohit2003 
Is anyone there who is assigned on the issue.
If not then I would like to give this a try.

**Comment by TheMohit2003** [comment]
Hey @ritikprajapat21 , I have already created a docker file for this . I am just waiting for project owners for their opinion.

**Comment by jvJUCA** [comment]
Dear @TheMohit2003 ,

Thank you for initiating the discussion and proposing the implementation of Docker support for our project. Our team fully supports this decision and believes it will greatly benefit both current and future contributors.

Having Docker support will streamline the setup process, making it easier for everyone to get started with the project regardless of their system configurations. This will undoubtedly enhance collaboration and ensure consistency across development environments.

We would be incredibly grateful if you could proceed with this contribution. Your effort in implementing Docker support will undoubtedly make a significant impact on the project, enabling smoother onboarding for contributors and fostering a more cohesive development experience.

If you need any assistance or have any questions throughout the process, please don't hesitate to reach out.

Once again, thank you for your initiative and dedication to improving our project.

Best regards,
@jvJUCA

**Comment by asr2003** [comment]
@TheMohit2003 Are you currently adding Docker support for dev env?

**Comment by TheMohit2003** [comment]
@asr2003 , yes .

**Comment by asr2003** [comment]
Waiting for your PR to look the approach you are followed

**Comment by abhisek-1221** [comment]
@TheMohit2003 Good initiative. Good Luck !

**Comment by TheMohit2003** [comment]
@jvJUCA Should we add Nginx to serve our Vue app, or just use `serve` with npm to expose it on a port?

**Comment by jvJUCA** [comment]
> @jvJUCA Should we add Nginx to serve our Vue app, or just use `serve` with npm to expose it on a port? I am talking about using nginx image in our `Dockerfile` to serve the build files.

Dear @TheMohit2003 ,

Our team prefers sticking with serve to expose our Vue application on a port. We've chosen this approach due to its simplicity and ease of configuration. serve is a lightweight and straightforward tool for serving static files, requiring minimal setup.

Best regards,
@jvJUCA

**Comment by Tufailahmed-Bargir** [comment]
hey @TheMohit2003 do you manage to do Docker setup??? I am also interested in doing so if you have no issues

**Comment by Tufailahmed-Bargir** [comment]
does doing Docker setup is challenging??

**Comment by xemyst** [comment]
> @Tufailahmed-Bargir , yep, already done . Will push it soon .

Sorry for late answering. :pray: 
A good option can be creating two docker images, one for dev, with the volume links to the current folder to dev locally. Another for deployment with a `nginx`server to serve the file.

**Comment by TheMohit2003** [comment]
@xemyst , i did asked the main members if we needed nginx , but they clearly said as of now they would want to keep the project image as simple as possible . So i am just exposing the build at a port without any nginx image.

**Comment by KarinePistili** [comment]
Hello, @TheMohit2003 you can follow up as described on the review of your PR: https://github.com/ruxailab/RUXAILAB/pull/395

**Comment by TheMohit2003** [comment]
@KarinePistili  yeah , I will  make changes to the file as said .
