### ISSUE TITLE
[QA] Improve performance and acessibility of website following suggestions by Lighthouse (or other provider)

### ISSUE THREAD

**Issue by KarinePistili** [ruxailab/RUXAILAB#371]
We would like to improve performance and acessiblity of RUXAILAB project. We would like help to improve the metrics that are suggested by providers such as Chrome's Lighhouse.

This issue became to life as mentioned by a contributor @pankaj87072 on discussion #370.

------------------------------------ Discussion message ----------------------------------------

hello @jvJUCA as i am analyzing the website performance and speed-test 
![Screenshot from 2024-03-12 21-42-15](https://github.com/ruxailab/RUXAILAB/assets/112722707/996f6d01-b388-4d2e-b436-449345571088)
![Screenshot from 2024-03-12 21-42-21](https://github.com/ruxailab/RUXAILAB/assets/112722707/a921d2b8-2715-4701-8947-44989b91b37c)

![Screenshot from 2024-03-12 21-42-24](https://github.com/ruxailab/RUXAILAB/assets/112722707/a6c7b5d1-f481-4c04-8d73-5c9ba08c72f2)
 i got this,so we can enhance the performance by doing minimal changes in 'css' only so i am suggesting the one's who is working on responsiveness should correct the code and use preloading and lazyloading method for the image loading

_Originally posted by @pankaj87072 in https://github.com/ruxailab/RUXAILAB/discussions/370#discussioncomment-8762258_

**Comment by pankaj87072** [comment]
@KarinePistili ohk mam i will work on it

**Comment by staru09** [comment]
Is this open to work?

**Comment by pankaj87072** [comment]
@staru09 srry but i am working on it

**Comment by pankaj87072** [comment]
@staru09 i can suggest you one more issue we can discuss on discussion panel.

**Comment by staru09** [comment]
> @staru09 i can suggest you one more issue we can discuss on discussion panel.

cool

**Comment by KarinePistili** [comment]
Great, keep us posted ;)

**Comment by pankaj87072** [comment]
@KarinePistili srry for late reply

**Comment by pankaj87072** [comment]
@KarinePistili hey i am trying to push my chagnes but getting an error of access i have checked form my side i have confiqured all access
![Screenshot from 2024-03-19 01-13-57](https://github.com/ruxailab/RUXAILAB/assets/112722707/0797ded8-6343-4ff8-80b5-2e6df65877c3)

**Comment by jvJUCA** [comment]
Dear @pankaj87072,

You need to fork the project and push your changes on your own fork, and after that you submit your pull request.

@jvJUCA

**Comment by pankaj87072** [comment]
@jvJUCA oh srry i totally forgot about it thanks for reminder.

**Comment by pankaj87072** [comment]
#399

**Comment by pankaj87072** [comment]
#399 added the preload for images

**Comment by pankaj87072** [comment]
@KarinePistili can you pls review it

**Comment by pankaj87072** [comment]
@KarinePistili can you pls review it

**Comment by KarinePistili** [comment]
Closing as it was already satisfied on #399
