### ISSUE TITLE
[🐞 BUG]: Deleting a heuristic not working.

### ISSUE THREAD

**Issue by RishabhJain0721** [ruxailab/RUXAILAB#375]
### Bug Description :
When I click on delete button, the heuristic is not actually being deleted. It is still present on firestore. 
Here is the screen recording of the same :

https://github.com/ruxailab/RUXAILAB/assets/107767172/c7b22159-6bef-4f0e-a02c-2162b3b2095f

**Comment by RishabhJain0721** [comment]
I am willing to fix this issue. @jvJUCA @KarinePistili Please assign this issue to me

**Comment by KarinePistili** [comment]
Hello @RishabhJain0721 , it is because you did not clicked the save button on the right bottom corner

**Comment by RishabhJain0721** [comment]
@KarinePistili Another thing that I want to point out. 
Suppose I am creating some heuristic and want to switch to some other tab(eg. Options tab in the video below), the heuristic just disappears. I think it may lead to some problem if someone is not aware of hitting the save button every time before changing the tab. 


https://github.com/ruxailab/RUXAILAB/assets/107767172/0ab66e69-c5bc-4675-86cd-dee645f62e5e


I was thinking that the heuristic should auto save every time the tab is changed. Should I create an issue regarding this?

**Comment by jvJUCA** [comment]
> @KarinePistili Another thing that I want to point out. Suppose I am creating some heuristic and want to switch to some other tab(eg. Options tab in the video below), the heuristic just disappears. I think it may lead to some problem if someone is not aware of hitting the save button every time before changing the tab.
> prob.mp4
> 
> I was thinking that the heuristic should auto save every time the tab is changed. Should I create an issue regarding this?

Dear @RishabhJain0721 ,

Thanks for highlighting this issue. It appears to be an existing problem that originated from previous contributors' implementation choices. However, addressing this issue has been pending for quite some time and warrants attention.

Could you please create an issue to address this longstanding issue? Your assistance in resolving this matter is much appreciated.

Best regards,
@jvJUCA

**Comment by RishabhJain0721** [comment]
> > @KarinePistili Another thing that I want to point out. Suppose I am creating some heuristic and want to switch to some other tab(eg. Options tab in the video below), the heuristic just disappears. I think it may lead to some problem if someone is not aware of hitting the save button every time before changing the tab.
> > prob.mp4
> > I was thinking that the heuristic should auto save every time the tab is changed. Should I create an issue regarding this?
> 
> Dear @RishabhJain0721 ,
> 
> Thanks for highlighting this issue. It appears to be an existing problem that originated from previous contributors' implementation choices. However, addressing this issue has been pending for quite some time and warrants attention.
> 
> Could you please create an issue to address this longstanding issue? Your assistance in resolving this matter is much appreciated.
> 
> Best regards, @jvJUCA

Alright then, I will create an issue for that.

**Comment by RishabhJain0721** [comment]
Hey @jvJUCA  I have created an issue regarding the bug mentioned above. Please have a look. 
Issue no. #376
