### ISSUE TITLE
[✨ FEATURE]: Implement Dependabot for Automated Dependency Updates

### ISSUE THREAD

**Issue by asr2003** [ruxailab/RUXAILAB#377]
### Feature Description 📝

Implement Dependabot support in the project to automate dependency updates.

### Motivation 🌟

The motivation behind this feature request is to ensure that our project's dependencies are regularly updated to include security patches, bug fixes, and new features. Dependabot will automate the process of monitoring and updating dependencies, reducing the manual effort required to keep our project up-to-date.

### Expected Behavior 🤔

1. Dependabot will periodically check for updates to our project's dependencies.
2. When updates are available, Dependabot will create pull requests to update the dependencies in our project.
3. We can review and merge these pull requests to incorporate the latest dependency versions into our project.

### Additional Information ℹ️

Dependabot is a widely-used tool in the open-source community for managing dependencies. By adding Dependabot support to our project, we can ensure that our dependencies are regularly updated and our project remains secure and up-to-date.

Thank you for considering this feature request! 🙌

**Comment by asr2003** [comment]
@jvJUCA @KarinePistili Please assign me this issue and would love to hear our thoughts on this feature

**Comment by KarinePistili** [comment]
Hello @asr2003 I think it is a good idea. I'll assign it to you

**Comment by RanitMukherjee** [comment]
Following the period of inactivity on this issue, I have submitted a PR to address it. Please review it at your convenience. Thank you!

**Comment by KarinePistili** [comment]
Closed as it was already satisfied on PR #412
