### ISSUE TITLE
[✨ FEATURE]: Adding Predefined Test for RUXAILAB Development Server

### ISSUE THREAD

**Issue by pankaj87072** [ruxailab/RUXAILAB#383]
### Feature Description 📝

Developers often spend a considerable amount of time setting up the development environment by giving test inputs .we can solve it by writing some predefined test and store it in file which is excessed after setting up dev server.

### Motivation 🌟

We can reduce time for writing test and it is frustating each time writing seting up the test .

### Expected Behavior 🤔

we will get predefined mail and password example test1@gmai.com pass:-test123 which consist of some template of test used by developers.

**Comment by pankaj87072** [comment]
@jvJUCA @marcgc21 @KarinePistili

**Comment by jvJUCA** [comment]
Ok @pankaj87072 assigned!

**Comment by KarinePistili** [comment]
Hello @pankaj87072 have you worked on this? If not I'll open to other contributors.

I've been thinking a good way to do this is to have an exported Firebase emulator folder. It would be helpful so people can have a head start with a populated db and auth.

https://firebase.google.com/docs/emulator-suite/install_and_configure?hl=pt-br#startup

**Comment by pankaj87072** [comment]
@KarinePistili i thought someone is working on it .

**Comment by pankaj87072** [comment]
@KarinePistili ohk i will do it if no one is working and srry i didn't see it earlier.

**Comment by KarinePistili** [comment]
There is no one working on it right now, at least not that I know. So you can go for it ;)
