### ISSUE TITLE
[🐞 BUG]: url link to the read documentation is invalid or showing 404 page not found..

### ISSUE THREAD

**Issue by Tufailahmed-Bargir** [ruxailab/RUXAILAB#386]
### Description 📝

when user clicks on read- documentation the link to that is showing page not found 

### Link 🔗

https://retlab-dev.firebaseapp.com/answers/documentation

### Steps to Reproduce 🔄

1. go to this Tests
2. select the HEURESTICS created by you 
3. scroll down to the ansers section
4. click on the read-documentation
5. see the error PAGE NOT FOUND

### Screenshots 📸

https://github.com/ruxailab/RUXAILAB/assets/142114244/33d93678-777a-4a8d-bd33-c7c77d32d122

### Expected Behavior 🤔

when user clicks on read-documentation the user must be taken to the actual documentation 

### Actual Behavior 😱

when user clciks on the read-documentation there is an error PAGE NOT FOUND

### Environment 🌍

windows 11
web browser : ms edge.

**Comment by karan-panda** [comment]
## Hey there, I'm Karan Panda.

Could you please assign this task to me? I believe I can work on fixing it promptly.

**Comment by Gaurav-Verma07** [comment]
Hii @Tufailahmed-Bargir , 
Great that you are interested in contributing at RUXAILAB.
It seems that no such route as `/documentation` exist in the project so 404 page is the expected behavior here.
Maybe documentation page will be added in the future so you can ask to implement that as a feature.

**Comment by Tufailahmed-Bargir** [comment]
@Gaurav-Verma07,  thanks for your valuable insights, Yes it must be a feature instead of bug report
