### ISSUE TITLE
Regarding Eye Tracking Data Visualization Tool

### ISSUE THREAD

**Issue by isha-talegaonkar** [ruxailab/RUXAILAB#401]
Hi!
I wanted to work on this idea from the GSOC ideas list but can see it has been crossed out. Can this be still worked upon?

Thanks!
Isha

**Comment by abhisek-1221** [comment]
Please don't create Issues for queries. Kindly discuss these things in Discord or the [Discussions Section](https://github.com/orgs/ruxailab/discussions) 

I request you to close this Issue. 

<img width="631" alt="Screenshot 2024-03-27 at 9 41 28 AM" src="https://github.com/ruxailab/RUXAILAB/assets/110292494/4d5f6a91-6cea-447b-bf6a-ca5a83973639">
