### ISSUE TITLE
[🐞 BUG]: Social and documentation links are not updated

### ISSUE THREAD

**Issue by KarinePistili** [ruxailab/RUXAILAB#413]
### Description 📝

Update links for Discord, e-mail and documentation across ruxailab website to use updated ones.

### Link 🔗

-

### Steps to Reproduce 🔄

-

### Screenshots 📸

-

### Expected Behavior 🤔

-

### Actual Behavior 😱

-

### Environment 🌍

-

**Comment by sushant4612** [comment]
Hey @KarinePistili, could you assign this to me?
