### ISSUE TITLE
[🐞 BUG]: remove effect that makes row bigger on hover in heuristics questions page

### ISSUE THREAD

**Issue by KarinePistili** [ruxailab/RUXAILAB#418]
### Description 📝

- It needs to always have the same size, not increasing on hover

### Link 🔗

-

### Steps to Reproduce 🔄

-

### Screenshots 📸

-

### Expected Behavior 🤔

-

### Actual Behavior 😱

-

### Environment 🌍

-

**Comment by Gaurav-Verma07** [comment]
Hey @KarinePistili , can I work on this?

**Comment by KarinePistili** [comment]
Oh sorry @Gaurav-Verma07 , this was suggested by @FernandaCasali so I already assigned it to her.
