### ISSUE TITLE
[✨ FEATURE]: Refactoring RUXAILAB Codebase from JavaScript to TypeScript

### ISSUE THREAD

**Issue by RanitMukherjee** [ruxailab/RUXAILAB#422]
### Feature Description 📝

TypeScript offers static typing, class-based object-oriented programming, and improved tooling, which can help us catch errors early in the development process and enhance code readability and maintainability.

Tasks:

- Code Analysis: Analyze the current JavaScript codebase to understand the structure, dependencies, and potential challenges in the refactoring process.
- Setup TypeScript Environment: Configure the necessary tooling and environment for TypeScript development, including the TypeScript compiler and linter.
- Refactor Code: Gradually refactor each JavaScript file to TypeScript. This includes:
>Adding type annotations to variables, function parameters, and return types.
>Refactoring classes and objects to use TypeScript’s class-based syntax where appropriate.
- Testing: Ensure that all unit tests and integration tests pass after refactoring. Add new tests if necessary.
- Code Review: Submit pull requests for each part of the codebase that is refactored, to allow for thorough code reviews.

### Motivation 🌟

Mastering the Codebase is crucial, and I am eager to take on this challenge by working extensively on it. This undertaking will require thorough planning and execution and may span multiple sprints. Collaborating with the maintainers and other contributors will not only help me achieve my goals but also enable me to gain valuable experience.

### Expected Behavior 🤔

Expected Outcome:

A more robust, maintainable codebase with improved developer experience due to the advantages of TypeScript.

### Additional Information ℹ️

Risks:

Potential risks include unforeseen complexities in the refactoring process, increased time for code reviews due to the large number of changes, and possible introduction of bugs if not properly tested.

**Comment by RanitMukherjee** [comment]
@KarinePistili @hvini Assign me this issue if you consider it something that needs to be worked on.

**Comment by KarinePistili** [comment]
Hello @RanitMukherjee , thank you for your suggestion. Refactoring the full code to another language is not a viable feature. Feel free to suggest features that improve or add new functionalities with the current codebase, without a full refactor.
