### ISSUE TITLE
[🐞 BUG]: doesn't allow editing option without value in heuristic tests.

### ISSUE THREAD

**Issue by FernandaCasali** [ruxailab/RUXAILAB#436]
### Description 📝

In heuristics testing, an option that has no value, does't allow you to edit it further after saving.

### Link 🔗

src\components\molecules\OptionsTable.vue

### Steps to Reproduce 🔄

- 

### Screenshots 📸

When you click to edit the option, nothing happens.

![image](https://github.com/ruxailab/RUXAILAB/assets/145176268/7bf9973d-aa52-41fd-b75b-88d1f4410690)

### Expected Behavior 🤔

- 

### Actual Behavior 😱

- 

### Environment 🌍

-

**Comment by SujashB** [comment]
Can I work on this issue?

**Comment by KarinePistili** [comment]
yes @SujashB , assigned!

**Comment by saltykheera** [comment]
@KarinePistili @SujashB this issue is not Comming in the dev-build. 

https://github.com/ruxailab/RUXAILAB/assets/142778969/e65a7d3c-4abb-46aa-9e99-4a5938dc2da2

**Comment by FernandaCasali** [comment]
Hey @saltykheera, it seems that in the the last merge, this issue has already been solved, but thanks for noticing!
