### ISSUE TITLE
[✨ FEATURE]: add rules to the options text field in heuristic tests.

### ISSUE THREAD

**Issue by FernandaCasali** [ruxailab/RUXAILAB#437]
### Feature Description 📝

To add a new option in heuristic test, the card says that hte limit for both text and description are 100 characters, but you can write more and click save, even though its red.

### Motivation 🌟

- allow writing more than 100 characters
- fix the rule to obey the limit

### Expected Behavior 🤔

- allow writing a maximum of 200 characters in **text**
- allow writing a maximum of 600 characters in **description**

**Comment by RanitMukherjee** [comment]
I would like to work on this one.

**Comment by KarinePistili** [comment]
Okay @RanitMukherjee , assigned to you!
