### ISSUE TITLE
Add dependencies label in the repository 

### ISSUE THREAD

**Issue by asr2003** [ruxailab/RUXAILAB#440]
### Feature Description 📝

Recently, we have got merged the dependabot which will checks for updates of packages in npm manger and makes a PR for them oncee they have any updates with dependency label.

### Motivation 🌟

The dependabot can't make a PR without adding respective dependency label as mentioned in the .github/dependabot.yml

### Expected Behavior 🤔

dependency label have to be added to test the working of dependabot in the repo

### Additional Information ℹ️

![image](https://github.com/ruxailab/RUXAILAB/assets/162500856/6959ea6b-6d0f-43fb-b910-c71cdcf33549)

**Comment by KarinePistili** [comment]
Thanks! Would you like to work on it as wel @asr2003 ?

**Comment by asr2003** [comment]
@KarinePistili I think only repo owners can add them. Similar like `'waiting for contributor' `label above add `dependencies` label

**Comment by KarinePistili** [comment]
Huum okay, like that?

**Comment by asr2003** [comment]
@KarinePistili  And also have any restrictions in our repo settings to make a PR. Because dependabot makes a automatic bot PR

**Comment by varshith257** [comment]
@KarinePistili

**Comment by asr2003** [comment]
@KarinePistili  PTAL
