### ISSUE TITLE
[🐞 BUG]: not showing all options when answering heuristic test

### ISSUE THREAD

**Issue by FernandaCasali** [ruxailab/RUXAILAB#444]
### Description 📝

When answering heuristic test, showing only 5 options and not all of then.

### Link 🔗

src\views\public\TestView.vue

### Steps to Reproduce 🔄

.

### Screenshots 📸

![image](https://github.com/ruxailab/RUXAILAB/assets/145176268/6fe7abd1-4571-4115-ac02-d5d8cec68580)

![image](https://github.com/ruxailab/RUXAILAB/assets/145176268/307eafbe-a4f1-41b5-b323-4bf260749673)

### Expected Behavior 🤔

.

### Actual Behavior 😱

.

### Environment 🌍

.

**Comment by RanitMukherjee** [comment]
@KarinePistili @jvJUCA Shouldn't implementing a scroll bar(utilizing CSS or Vue-specific library) on the answer card prevent this type of behavior? 
Let me know if this course of action is in tune with solving the Bug at hand or if some changes are to be made. 
If it's all good to go, could you assign me the issue and I will submit a PR against the same.

**Comment by KarinePistili** [comment]
Hello @RanitMukherjee it was a problem with the data passed which had values that would repeat, and then the component would treat them as duplicates. @jvJUCA have fixed it alongside other commits these past week.

But thanks for suggesting a fix anyway
