### ISSUE TITLE
[🐞 BUG]: randon order in evaluator table (heuristic test)

### ISSUE THREAD

**Issue by FernandaCasali** [ruxailab/RUXAILAB#448]
### Description 📝

Randon order in usability percentage evaluator table, the calculus is right but the order is not

### Link 🔗

. 

### Steps to Reproduce 🔄

.

### Screenshots 📸

.

### Expected Behavior 🤔

.

### Actual Behavior 😱

.

### Environment 🌍

.

**Comment by shahbazshaik17** [comment]
Can I have this issue @KarinePistili
