### ISSUE TITLE
[🐞 BUG]: Invite link expired and typo

### ISSUE THREAD

**Issue by dakshsinghrathore** [ruxailab/RUXAILAB#453]
### Description 📝

When users navigate to the answer tab, they may find that the _Discord invite link has expired_. Additionally, there's a **typo** in the word _'community'._

### Link 🔗

src/locales/en.json

### Steps to Reproduce 🔄

1. Go to any Demo Test 
2. Click on 'Answers'
3. Scroll down to 'Learn More'

### Screenshots 📸

**comunity** ➡️ **community**

![Screenshot from 2024-04-20 23-16-12](https://github.com/ruxailab/RUXAILAB/assets/115932772/1d2f80cb-fa89-4010-b4e9-2c16192e59ae)

**DISCORD** link expired

![image](https://github.com/ruxailab/RUXAILAB/assets/115932772/9a8f7ad9-5e50-43f5-a8ee-ee9a8f93e5d8)

### Expected Behavior 🤔

**_FIXED TYPO_** 👇🏽 

![image](https://github.com/ruxailab/RUXAILAB/assets/115932772/839e21d2-2550-493e-ba76-18fdfd5eb614)

**_FIXED LINK_** 👇🏽 

![image](https://github.com/ruxailab/RUXAILAB/assets/115932772/425d0840-e1d9-44e5-a9df-38321a3c0983)

### Actual Behavior 😱

.

### Environment 🌍

- Vue component : `src/locales/en.json`
- OS : Ubuntu
- Browser: Brave
- Git Branch : develop

### Additional Information ℹ️

I would like to work on this issue, kindly assign it to me !

**Comment by jvJUCA** [comment]
OK, Assigned please put this invitation link, https://discord.gg/MFWNpwTq9q it never expires!
