### ISSUE TITLE
fix: reduce padding/margin heuristic row

### ISSUE THREAD

**Issue by marcgc21** [ruxailab/RUXAILAB#481]
Comparing heuristic and questions rows we can see that heuristics are bigger that questions.
<img width="831" alt="Screenshot 2024-05-26 at 13 02 17" src="https://github.com/ruxailab/RUXAILAB/assets/7767051/da206e05-616a-4127-9fd8-c1bd3dedaa34">

**Comment by saltykheera** [comment]
issue #483 fixed
https://github.com/ruxailab/RUXAILAB/pull/483

**Comment by saltykheera** [comment]
![image](https://github.com/ruxailab/RUXAILAB/assets/142778969/5dbeef59-11ff-4793-8ddd-43d796ae6a74)
fixed padding
