### ISSUE TITLE
fix: I can not edit tests, neither heuristics

### ISSUE THREAD

**Issue by marcgc21** [ruxailab/RUXAILAB#482]
<img width="1370" alt="Screenshot 2024-05-26 at 13 05 22" src="https://github.com/ruxailab/RUXAILAB/assets/7767051/33887d45-957f-4d89-bc4d-ecada93019e6">

**Comment by KarinePistili** [comment]
@marcgc21 Does your test have answers? If a test already have answers it is not editable
