### ISSUE TITLE
[✨ FEATURE]: Dark Mode

### ISSUE THREAD

**Issue by saltykheera** [ruxailab/RUXAILAB#487]
### Feature Description 📝

Implementing Dark Mode transforms the interface to use darker colors, providing several key benefits.

### Motivation 🌟

The process of filling out heuristic evaluations can be lengthy and exhausting. Many candidates prefer darker screen colors, making the implementation of Dark Mode beneficial. Dark Mode can reduce eye strain, decrease screen glare, and save battery life on devices with OLED or AMOLED screens.

### Expected Behavior 🤔

Dark Mode darker colors

### Additional Information ℹ️

Test the UI before deploying changes

**Comment by saltykheera** [comment]
https://github.com/ruxailab/RUXAILAB/assets/142778969/50bced10-cbc9-4691-b127-05b6b8c61bbf

**Comment by saltykheera** [comment]
stable at 
- [x] /testslist   
- [x] /testview   directory src src\views\public\TestView.vue

**Comment by jvJUCA** [comment]
I really like the idea of having a dark mode, but if it is implemented, it needs to be globally compatible.

**Comment by tejasathalye** [comment]
hey @jvJUCA @saltykheera can i look into this issue to fix? can you assign it to me?

**Comment by saltykheera** [comment]
> hey @jvJUCA @saltykheera can i look into this issue to fix? can you assign it to me?

the moderators are in_active 
go ahead and fix the issue raise a pr 
i assure you if it done correctly 
IT will be merged @tejasathalye

**Comment by tejasathalye** [comment]
@saltykheera Yeah sure! I'll look into it
Thanks!😄
