### ISSUE TITLE
[✨ FEATURE]: Add a Submit Page when User Submit the heuristics 

### ISSUE THREAD

**Issue by saltykheera** [ruxailab/RUXAILAB#497]
### Feature Description 📝

Add a confirmation page that displays a "Your response has been recorded" message after a user submits the feedback form.

### Motivation 🌟

Currently, after submitting the heuristics form, users remain on the same page without any indication that their submission was successful. This can cause confusion and uncertainty about whether their feedback was received. A confirmation page will provide clear feedback to the user, improving the overall user experience.

### Expected Behavior 🤔

After a user submits the heuristics form, they should be redirected to a new page that displays a message confirming that their response has been recorded. This page should be simple and clear, ensuring users know their submission was successful.

### Additional Information ℹ️

[screen-recorder-tue-jun-11-2024-18-36-45.webm](https://github.com/ruxailab/RUXAILAB/assets/142778969/2ec90cb8-a20e-41ee-ad92-1905c9e194b3)

**Comment by jvJUCA** [comment]
Maybe a redirect to testslist with a success toast will be fine
