### ISSUE TITLE
[🐞 BUG]: Confusing Routes "/home" and "/"

### ISSUE THREAD

**Issue by saltykheera** [ruxailab/RUXAILAB#500]
### Description 📝

2 confusing routes are available /home and /

### Link 🔗

https://ruxailab-prod.firebaseapp.com/home

### Steps to Reproduce 🔄

/home leads to views = homepage 
/ leads to views = landing page 

### Screenshots 📸

![image](https://github.com/ruxailab/RUXAILAB/assets/142778969/02bc41e9-1193-44c2-a2b6-9a38621dfd59)
![image](https://github.com/ruxailab/RUXAILAB/assets/142778969/93247007-1658-4135-a13f-ae05c5fc9059)

### Expected Behavior 🤔

isnt both leads to the landing page 

### Actual Behavior 😱

both leading to different pages

### Environment 🌍

src/views/landingpage

src/views/homepage

**Comment by jvJUCA** [comment]
Oh this /home is a fossil of the code. Please remove it in your next pull request.

**Comment by jvJUCA** [comment]
f
