### ISSUE TITLE
[🐞 BUG]: No info is Provided to User if Final Report is failed to generate

### ISSUE THREAD

**Issue by saltykheera** [ruxailab/RUXAILAB#507]
### Description 📝

No information is provided to the user if the final report fails to generate.

### Link 🔗

https://ruxailab-prod.firebaseapp.com/finalreportview/:testid

### Steps to Reproduce 🔄

Attempt to generate the final report.

- [x] Tick mark all

Observe that no feedback is given if the report generation fails.

### Screenshots 📸

![image](https://github.com/ruxailab/RUXAILAB/assets/142778969/fddfabfe-75ed-41a4-adb6-b3f11a753375)

### Expected Behavior 🤔

Users should receive a clear error message indicating that the final report generation has failed and provide possible reasons or next steps.

### Actual Behavior 😱

The application fails silently, providing no feedback or error message to the user when the final report cannot be generated.

### Environment 🌍

src\views\admin\FinalReportView.vue

### Additional Information ℹ️

Implement error handling to catch report generation failures.
Display a user-friendly error message explaining the issue.
Optionally, suggest steps to resolve the issue or contact support for assistance.

**Comment by jvJUCA** [comment]
We need to fix that on the pdf generator repository, is a laravel project!

**Comment by saltykheera** [comment]
@jvJUCA for now how about adding just a simple Toast for error

**Comment by jvJUCA** [comment]
I think it would be useful to show the feedback to the user. If you can resolve this problem, I would be thankful.

**Comment by saltykheera** [comment]
@jvJUCA 
Onselecting these options
![image](https://github.com/ruxailab/RUXAILAB/assets/142778969/143e7e5c-ba5a-41fe-8526-4fb5a1e75ac9)
the server respond with ERROR:500 internal server Error.

> but if we individually generate the pdf [ by taking test Options or answer by evaluator ] it does not creates an error 
 among all possible combinations

> if these two are checked it causes the error 
> futher more ON checking Test OPTIONS , the pdf doesnt contains the test option

**Comment by jvJUCA** [comment]
> @jvJUCA Onselecting these options ![image](https://private-user-images.githubusercontent.com/142778969/340691579-143e7e5c-ba5a-41fe-8526-4fb5a1e75ac9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MjE1NjEsIm5iZiI6MTcxODcyMTI2MSwicGF0aCI6Ii8xNDI3Nzg5NjkvMzQwNjkxNTc5LTE0M2U3ZTVjLWJhNWEtNDFmZS04NTI2LTRmYjVhMWU3NWFjOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOFQxNDM0MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iM2ExMjQyOTRhMjhmYzMxZTYzNTc3NzM0ZDdjMDg3ZDUyMTUyNTg5Y2FkZGU5NTAzNjAwNTUzNjIwZWUxOGQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8tK0wKXzVXo8nS4tYd1sNR-vyEvLoCfie39LyvmILjg) the server respond with ERROR:500 internal server Error.
> 
> > but if we individually generate the pdf [ by taking test Options or answer by evaluator ] it does not creates an error
> > among all possible combinations
> 
> > if these two are checked it causes the error
> > futher more ON checking Test OPTIONS , the pdf doesnt contains the test option

Thanks for debugging, i will create a issue on the pdf laravel project!

**Comment by saltykheera** [comment]
[https://github.com/ruxailab/laravel-pdf-generator/pull/3](url)

Related PR

**Comment by saltykheera** [comment]
@jvJUCA PR for this issue has been raised in the laravel repo 
please review that changes
