### ISSUE TITLE
Implement edit template

### ISSUE THREAD

**Issue by KarinePistili** [ruxailab/RUXAILAB#59]

**Comment by varshith257** [comment]
@KarinePistili @jvJUCA Can I get the info about what exactly have to do to edit the template?

I would like to take this issue

**Comment by Jaishree2310** [comment]
@jvJUCA  I can take this issue, please assign this to me. Thank you

**Comment by jvJUCA** [comment]
> @jvJUCA @KarinePistili I can take this issue, please assign this to me. Thank you

Ok, assigned!

**Comment by Jaishree2310** [comment]
Hi, @jvJUCA can you brief me more in detail about this issue?
I'm ready to work on this as I'm already doing for the unmoderated templates so it will be easy for me to make changes accordingly.

**Comment by KarinePistili** [comment]
Hello @Jaishree2310 I realized this issue is almost a duplicate of the other one we were talking about. I'll close this one and we continue our conversation there, okay? https://github.com/ruxailab/RUXAILAB/issues/153
